import { useState, useCallback } from 'react';
import { FacilityFormData, FormUIState } from '../types/facilityTypes';
import { VALIDATION_RULES, COORDINATE_BOUNDS } from '../constants/serviceConstants';

const initialFormData: FacilityFormData = {
  name: '',
  phone: '',
  email: '',
  address: '',
  openingHoursType: '24hours',
  customOpeningHours: '',
  ownership: '',
  username: '',
  password: '',
  latitude: '',
  longitude: '',
  type: 'hospital',
  hospitalType: '',
  pharmacyType: '',
  services: [],
  emergency: false,
  agentId: '', // Will be generated by backend
  notes: ''
};

const initialFormUIState: FormUIState = {
  tabValue: 0,
  showPassword: false,
  servicesDone: false,
  validationErrors: [],
  isSubmitting: false,
  isDetectingLocation: false
};

export const useFacilityForm = (initialTab: number = 0, initialType: 'hospital' | 'pharmacy' = 'hospital') => {
  const [formData, setFormData] = useState<FacilityFormData>({ ...initialFormData, type: initialType });
  const [formUIState, setFormUIState] = useState<FormUIState>({ ...initialFormUIState, tabValue: initialTab });

  const resetForm = useCallback(() => {
    setFormData(initialFormData);
    setFormUIState(initialFormUIState);
  }, []);

  const updateFormField = useCallback((field: keyof FacilityFormData, value: any) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  }, []);

  const updateFormUIState = useCallback((updates: Partial<FormUIState>) => {
    setFormUIState(prev => ({
      ...prev,
      ...updates
    }));
  }, []);

  const handleTabChange = useCallback((newValue: number) => {
    const newType = newValue === 0 ? 'hospital' : 'pharmacy';
    
    setFormData(prev => ({
      ...prev,
      type: newType as 'hospital' | 'pharmacy',
      hospitalType: newType === 'hospital' ? prev.hospitalType : '',
      pharmacyType: newType === 'pharmacy' ? prev.pharmacyType : '',
      services: []
    }));
    
    setFormUIState(prev => ({
      ...prev,
      tabValue: newValue,
      servicesDone: false,
      validationErrors: []
    }));
  }, []);

  const handleInputChange = useCallback((field: string) => (event: any) => {
    const value = event.target.value;
    updateFormField(field as keyof FacilityFormData, value);
  }, [updateFormField]);

  const handlePhoneChange = useCallback((event: any) => {
    let value = event.target.value;
    // Remove any non-digit characters
    value = value.replace(/\D/g, '');
    
    // Limit to exactly 9 digits and ensure it starts with 9 or 7
    if (value.length <= VALIDATION_RULES.PHONE_LENGTH) {
      // Only allow if it's empty, starts with 9, or starts with 7
      if (value === '' || (value.length >= 1 && VALIDATION_RULES.PHONE_PREFIXES.some(prefix => value.startsWith(prefix)))) {
        updateFormField('phone', value);
        
        // Clear phone validation error if valid
        if (formUIState.validationErrors.includes('phone') && value.length === VALIDATION_RULES.PHONE_LENGTH && VALIDATION_RULES.PHONE_PREFIXES.some(prefix => value.startsWith(prefix))) {
          setFormUIState(prev => ({
            ...prev,
            validationErrors: prev.validationErrors.filter(err => err !== 'phone')
          }));
        }
      }
    }
  }, [updateFormField, formUIState.validationErrors]);

  const handleEmailChange = useCallback((event: any) => {
    const value = event.target.value;
    updateFormField('email', value);
    
    // Clear email validation error if valid
    if (formUIState.validationErrors.includes('email') && isValidEmail(value)) {
      setFormUIState(prev => ({
        ...prev,
        validationErrors: prev.validationErrors.filter(err => err !== 'email')
      }));
    }
  }, [updateFormField, formUIState.validationErrors]);

  const handleServiceToggle = useCallback((service: string) => {
    setFormData(prev => ({
      ...prev,
      services: prev.services.includes(service)
        ? prev.services.filter(s => s !== service)
        : [...prev.services, service]
    }));
    
    // Clear validation error if services are selected
    if (formUIState.validationErrors.includes('services')) {
      setFormUIState(prev => ({
        ...prev,
        validationErrors: prev.validationErrors.filter(err => err !== 'services')
      }));
    }
  }, [formUIState.validationErrors]);

  const handleLocationDetect = useCallback(() => {
    if (navigator.geolocation) {
      setFormUIState(prev => ({ ...prev, isDetectingLocation: true }));
      
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const lat = position.coords.latitude.toFixed(6);
          const lng = position.coords.longitude.toFixed(6);
          
          setFormData(prev => ({
            ...prev,
            latitude: lat,
            longitude: lng
          }));
          
          // Clear location validation errors if they exist
          setFormUIState(prev => ({
            ...prev,
            isDetectingLocation: false,
            validationErrors: prev.validationErrors.filter(err => err !== 'latitude' && err !== 'longitude')
          }));
          
          showToast('Location detected successfully!', 'success');
        },
        (error) => {
          console.error('Error getting location:', error);
          setFormUIState(prev => ({ ...prev, isDetectingLocation: false }));
          
          let errorMessage = 'Unable to detect location. Please enter manually.';
          if (error.code === 1) {
            errorMessage = 'Location access denied. Please enable location permissions.';
          } else if (error.code === 2) {
            errorMessage = 'Location unavailable. Please enter manually.';
          } else if (error.code === 3) {
            errorMessage = 'Location request timed out. Please try again.';
          }
          
          showToast(errorMessage, 'error');
        }
      );
    } else {
      showToast('Geolocation is not supported by your browser.', 'error');
    }
  }, []);

  const getCurrentServices = useCallback(() => {
    const { HOSPITAL_SERVICE_MAP, PHARMACY_SERVICE_MAP } = require('../constants/serviceConstants');
    const typeKey = formData.type === 'hospital' ? formData.hospitalType : formData.pharmacyType;
    const serviceMap = formData.type === 'hospital' ? HOSPITAL_SERVICE_MAP : PHARMACY_SERVICE_MAP;
    return typeKey ? (serviceMap[typeKey] || []) : [];
  }, [formData.type, formData.hospitalType, formData.pharmacyType]);

  const isValidEmail = (email: string): boolean => {
    if (!email.trim()) return false;
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  const isValidPassword = (password: string): boolean => {
    if (!password) return true;
    
    const minLength = VALIDATION_RULES.PASSWORD_MIN_LENGTH;
    const hasUpperCase = /[A-Z]/.test(password);
    const hasLowerCase = /[a-z]/.test(password);
    const hasNumber = /\d/.test(password);
    const hasSpecialChar = /[!@#$%^&*(),.?":{}|<>]/.test(password);
    
    if (password.length < minLength) return false;
    if (!hasUpperCase) return false;
    if (!hasLowerCase) return false;
    if (!hasNumber) return false;
    if (!hasSpecialChar) return false;
    
    return true;
  };

  const validateForm = useCallback((): string[] => {
    const errors: string[] = [];
    
    if (!formData.name.trim()) errors.push('name');
    
    // Email validation (required)
    if (!formData.email.trim()) {
      errors.push('email');
    } else if (!isValidEmail(formData.email)) {
      errors.push('email');
    }
    
    // Phone validation (optional - only validate if provided)
    if (formData.phone.trim() && (formData.phone.length !== VALIDATION_RULES.PHONE_LENGTH || (!VALIDATION_RULES.PHONE_PREFIXES.some(prefix => formData.phone.startsWith(prefix))))) {
      errors.push('phone');
    }
    
    if (!formData.address.trim()) errors.push('address');
    
    // Opening hours validation
    if (!formData.openingHoursType) {
      errors.push('openingHoursType');
    } else if (formData.openingHoursType === 'custom' && !formData.customOpeningHours.trim()) {
      errors.push('customOpeningHours');
    }
    
    if (!formData.ownership.trim()) errors.push('ownership');
    if (!formData.username.trim()) errors.push('username');
    
    // Agent ID is now generated by backend, no validation needed
    
    // Validate latitude and longitude
    if (!formData.latitude.trim()) {
      errors.push('latitude');
    } else {
      const lat = parseFloat(formData.latitude);
      if (isNaN(lat) || lat < COORDINATE_BOUNDS.LAT_MIN || lat > COORDINATE_BOUNDS.LAT_MAX) {
        errors.push('latitude');
      }
    }
    
    if (!formData.longitude.trim()) {
      errors.push('longitude');
    } else {
      const lng = parseFloat(formData.longitude);
      if (isNaN(lng) || lng < COORDINATE_BOUNDS.LNG_MIN || lng > COORDINATE_BOUNDS.LNG_MAX) {
        errors.push('longitude');
      }
    }
    
    if (formData.type === 'hospital' && !formData.hospitalType) errors.push('hospitalType');
    if (formData.type === 'pharmacy' && !formData.pharmacyType) errors.push('pharmacyType');
    
    if (formData.services.length === 0) errors.push('services');
    
    // Validate password if provided (optional but must be strong if provided)
    if (formData.password && !isValidPassword(formData.password)) {
      errors.push('password');
    }
    
    return errors;
  }, [formData]);

  const isFormValid = useCallback(() => {
    return validateForm().length === 0;
  }, [validateForm]);

  const createFacilityObject = useCallback(() => {
    const facilityId = `FAC-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
    
    return {
      ...formData,
      _id: facilityId,
      agentId: facilityId,
      openingHours: formData.openingHoursType === '24hours' 
        ? '24 hours' 
        : formData.customOpeningHours,
      location: {
        type: 'Point',
        coordinates: [parseFloat(formData.longitude), parseFloat(formData.latitude)]
      },
      isActive: true,
      createdAt: new Date().toISOString(),
      emergency: formData.emergency,
      notes: formData.notes || undefined,
      password: formData.password || undefined,
      profileImage: formData.profileImage || undefined,
      galleryImages: formData.galleryImages || []
    };
  }, [formData]);

  return {
    // State
    formData,
    formUIState,
    
    // Actions
    resetForm,
    updateFormField,
    updateFormUIState,
    handleTabChange,
    handleInputChange,
    handlePhoneChange,
    handleEmailChange,
    handleServiceToggle,
    handleLocationDetect,
    getCurrentServices,
    validateForm,
    isFormValid,
    createFacilityObject,
    
    // Utilities
    isValidEmail,
    isValidPassword
  };
};

// Helper function for toast notifications
const showToast = (message: string, type: 'success' | 'error') => {
  try {
    window.dispatchEvent(new CustomEvent('admin:toast', { 
      detail: { type, message } 
    }));
  } catch(e) {}
};
